version: '3'
services:   
    redis:
         image: redis:3.2
         restart: always
         ports:
             - "6379:6379"
         volumes:
             - ./data:/data
    mongo:
        image: mongo:3.5.13
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./db:/data/db
    mysql: 
        image: mysql:5.7
        restart: always
        environment: 
                MYSQL_ROOT_PASSWORD: root
        ports: 
            - "3306:3306"
